# Schöne URLs → echte Dateien
[[redirects]]
  from = "/kontakt"
  to = "/kontakt.html"
  status = 200

[[redirects]]
  from = "/impressum"
  to = "/impressum.html"
  status = 200

[[redirects]]
  from = "/datenschutz"
  to = "/datenschutz.html"
  status = 200
