# netlify.toml  (im Projekt-Root!)

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# (Optional) Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"

# (Optional) Caching für Assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
